### ISSUE TITLE
example code to integrate grpctunnel

### ISSUE THREAD

**Issue by dliu2223** [openconfig/grpctunnel#10]
Hi,

please include examples to show how to migrate current gRPC client and server to grpcTunnel, e.g., in client, current code dials to server IP address and in server, it listens for the connection request, some sample code segments would really help.

Thanks

David

**Comment by aaronbee** [comment]
From @gcsl :
Repositories with example code.
github.com/openconfig/grpctunnel
github.com/openconfig/gnmi

gNMI server - embedded tunnel client used as an additional TCP listener
* https://github.com/openconfig/gnmi/blob/master/testing/fake/gnmi/agent.go#L90

gNMI collector
Embedded tunnel server
* https://github.com/openconfig/gnmi/blob/master/cmd/gnmi_collector/gnmi_collector.go#L138

A custom dialer over a tunnel
* https://github.com/openconfig/gnmi/blob/master/cmd/gnmi_collector/gnmi_collector.go#L334
* https://github.com/openconfig/gnmi/blob/master/client/gnmi/client.go#L88

**Comment by dliu2223** [comment]
Thanks

David
