### ISSUE TITLE
missing Capabilities message in tunnel.proto

### ISSUE THREAD

**Issue by dliu2223** [openconfig/grpctunnel#12]
The Capabilities message was defined in previous version as
message Capabilities {
  bool handler = 1;  // Whether a handler is installed on the endpoint.
}
Should the Capabilities defined in gNMI be used in this proposal

Thanks

David

**Comment by gcsl** [comment]
Capabilities message in gRPC tunnel had no correlation with the
Capabilities RPC in gNMI and the name conflict was coincidental. The
original intent of Capabilities message in this prototype tunnel library
was to allow for a single target to enumerate multiple protocols (e.g.
gNMI/gNOI and ssh). But that was subsumed in the update where the tunnel
target can enumerate a type specifically and register itself multiple times
for each protocol.  Thus Capabilities message was removed.

**Comment by dliu2223** [comment]
Thanks

David
