### ISSUE TITLE
Suggestion: Split tunnel.Client.Run into two methods

### ISSUE THREAD

**Issue by aaronbee** [openconfig/grpctunnel#14]
I wasn't exactly sure which repo to put this issue.

There is some code in [gnmi/tunnel.go](https://github.com/openconfig/gnmi/blob/88610ee25fee502f3aaa09e9a339e5cf0fd2fa73/tunnel/tunnel.go#L141) that busy loops and is data racey.

```
	// Monitor if the client is registered.
	go func() {
		for {
			if client.Registered {
				started <- true
				return
			}
		}
	}()

	if err = client.Run(ctx); err != nil {
		chErr <- err
		return
	}
```
This will burn a CPU core waiting for client.Registered to be set and it is an unprotected read of client.Registered, which is written by a different goroutine.

One way tunnel.Client could be refactored to avoid this issue entirely is to split up Client.Run into two functions. One function does the setup and then returns (what is currently in the body Client.Run before the call to Client.start). Another that runs the proxy client, what currently exists in Client.start. With these two separate functions the above code in from the gnmi repository could be simply:

```
if err := client.Register(); err != nil { return err }
started <- true
return client.Run()
```
(I'm also not a fan of error channels. Most of the time code with error channels can be refactored into a function that just returns an error.)

**Comment by gcsl** [comment]
Thanks, Aaron. Yes, I think some refactoring is in order. We'll include you on a PR.

**Comment by gcsl** [comment]
Done in https://github.com/openconfig/grpctunnel/pull/17
