### ISSUE TITLE
TargetType is not used in message target

### ISSUE THREAD

**Issue by dliu2223** [openconfig/grpctunnel#16]
Please explain why target_type is a string instead of the enum TargetType

Thanks

David

enum TargetType {
  UNKNOWN = 0;
  // https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=22
  SSH = 22;
  // https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=9339
  GNMI_GNOI = 9339;
}
message Target {
  enum TargetOp {
    UNKNOWN = 0;
    ADD = 1;
    REMOVE = 2;
  }
  TargetOp op = 1;
  // Used to ack the registration of target_id and target_type.
  bool accept = 2;
  // Target id identifies which handler to use for a tunnel stream.
  string target_id = 3;
  // String value of the corresponding TargetType for a standard protocol.
  // A non-enumerated protocol is supported so long as both tunnel client and
  // server are in agreement on a particular value.
  string target_type = 4;
  string error = 5;
}

**Comment by gcsl** [comment]
The enum allows for retrieving a string constant for a set of defined
types.  e.g.
https://github.com/openconfig/gnmi/blob/master/testing/fake/gnmi/agent.go#L89

However, by allowing the target type to be a string, an operator could also
tunnel other protocols not in the enum so long as the client and server
agreed on common type strings.

**Comment by dliu2223** [comment]
Thank you for the explanation. I was planning to extend the enum to support OpenFlow and P4 for data plane programming through gRPC tunnel, will switch to string for now, maybe submit changes in the future when implementation is done.

David

**Comment by gcsl** [comment]
The intention is to allow for expansion of the enum and both P4 and
Openflow would be potential candidates.
