### ISSUE TITLE
Suggestion to add versioning number to tunnel.proto

### ISSUE THREAD

**Issue by gwizdms** [openconfig/grpctunnel#18]
To help track vendor development of tunnel.proto could we please add a version number for referencing development efforts and future changes.

**Comment by gcsl** [comment]
Hello Greg,

Does adding a version as a proto comment in this PR satisfy your request?

**Comment by gwizdms** [comment]
Carl,

That would be fine.  Thank you.

Greg


Gregory Soroka
DMTS – Verizon Network Infrastructure Planning
Telemetry, Analytics and Automation NGM/UT/NGPON2
Contact (518) 728-2902

This message may contain privileged and confidential information intended only for the recipients.  If you are not the intended recipient or the person responsible for delivery of this message to the intended recipient, please delete this message and do not distribute, copy or retain this message.  If you received this message in error, please notify me by email.
