### ISSUE TITLE
support mTLS in tunnel.Listen()

### ISSUE THREAD

**Issue by dliu2223** [openconfig/grpctunnel#39]
func Listen(ctx context.Context, addr string, cert string, targets map[Target]struct{}) (net.Listener, error)
only accepts cert string as the credential input for grpc.DialOption; for mTLS implementation on agent/tunnel client, should tlc.Config be supported as input?

On the collector/tunnel server side, it is OK, the mTLS can be configured for the grpc.NewServer()

**Comment by gcsl** [comment]
We are looking into adding mTLS support and some additional examples.

**Comment by dliu2223** [comment]
thanks

**Comment by jxx-gg** [comment]
FYI, we have added an example for mTLS. I will close the issue for now. Please feel free to reopen or create a new issue if needed.

**Comment by dliu2223** [comment]
Thanks

David

On Mon, Sep 27, 2021 at 7:15 AM Johnson Xu ***@***.***> wrote:

> FYI, we have added an example for mTLS. I will close the issue for now.
> Please feel free to reopen or create a new issue if needed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_openconfig_grpctunnel_issues_39-23issuecomment-2D927917786&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=muzbAtqPojeg0y31fUcbZA_FaWC9exft3yCCrqM_26s&m=hfpDUl-5UQIWO7tzZT27Onqnl3PXoxYXkf7IQLQaXVk&s=LCXT5FDKL4a7gqcHtEOZIfVPv32vD-dz_Tr4H8YucAc&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEN56COZJ56OHFW2OVOCNS3UEB4APANCNFSM5DHMW3AQ&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=muzbAtqPojeg0y31fUcbZA_FaWC9exft3yCCrqM_26s&m=hfpDUl-5UQIWO7tzZT27Onqnl3PXoxYXkf7IQLQaXVk&s=BjKlTzF3pvbw_o0nvPzizAnxIYDJDAyMTsZqGth6Nh4&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=muzbAtqPojeg0y31fUcbZA_FaWC9exft3yCCrqM_26s&m=hfpDUl-5UQIWO7tzZT27Onqnl3PXoxYXkf7IQLQaXVk&s=ioosvIiBcVSO3IE1XRY-fawPBB2dbLsSL6-T9ou-JwE&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=muzbAtqPojeg0y31fUcbZA_FaWC9exft3yCCrqM_26s&m=hfpDUl-5UQIWO7tzZT27Onqnl3PXoxYXkf7IQLQaXVk&s=vVPQtz86uDfNeDDoeixN8k4Xfajk61ObU39agtZSBWA&e=>.
>
>


-- 
David Liu
