### ISSUE TITLE
gnmi-collector would churn with multiple tunnel clients

### ISSUE THREAD

**Issue by peichengATgit** [openconfig/grpctunnel#52]
The gnmi-collector churns when there exist multiple tunnel targets.
It keeps flapping the tunnel targets (clients).

Scenario:
1 tunnel server : using https://github.com/openconfig/gnmi/tree/master/cmd/gnmi_collector
2 tunnel client :  using use https://github.com/openconfig/grpctunnel/tree/master/cmd/target
with ID/Type = {target1, GNMI_GNOI} and {target2, GNMI_GNOI}, respectively

Cause:
(1) Upon a new target is registered, the gnmi-collector calls tunnel.ServerConn().
This internally calls NewSession(), which sends register request to all clients without checking their capability.
https://github.com/openconfig/grpctunnel/blob/dabbeee33dab4d2971091748774b18bd3cb701cc/tunnel/tunnel.go#L1014
(2) The target would reject the request if it does not own the target id.
https://github.com/openconfig/grpctunnel/blob/dabbeee33dab4d2971091748774b18bd3cb701cc/cmd/target/target.go#L91

Example Sequence:
1. target1 register {target1, GNMI_GNOI} to the server
2. There exist only one client. The server sends request {target1, GNMI_GNOI} to target1
3. target1 accepts the request. The tunnel is established.

....

4. target2 register {target2, GNMI_GNOI} to the server
5. Now, there exist total two clients. The sever sends request {target2, GNMI_GNOI} to both target1 and target2 due to the above logic in code (1)
6. target1 rejects the request, due to above code (2).  while target2 accepts the request.
7. target1's current connection got impacted/canceled.  target2's tunnel is established.

....
8. After sometime, target1 retries.
9. Again, now there exist total two clients. The sever sends request {target1, GNMI_GNOI} to both target1 and target2
10. This time, instead, target2 rejects the request as it does not support "target1",   while  target1 accepts.
11. target2 got canceled. and target1's tunnel is established.

This continues, and keeps flapping the targets alternatively.
To workaround the issue, I need to add additional check in code (1), to not send the request to the clients which don't support the target/type combination.

**Comment by jxx-gg** [comment]
Thanks for the feedback. https://github.com/openconfig/grpctunnel/pull/53 will try to address this.
