### ISSUE TITLE
Potential data race in tunnel.Server

### ISSUE THREAD

**Issue by karimra** [openconfig/grpctunnel#54]
Hi,

The [clients map](https://github.com/openconfig/grpctunnel/blob/master/tunnel/tunnel.go#L283) defined under `tunnel.Server` is accessed concurrently for read and write in the case `NewSession` and `Register` functions are called simultaneously.
Read access happens [here](https://github.com/openconfig/grpctunnel/blob/master/tunnel/tunnel.go#L1001)
Write access happens [here](https://github.com/openconfig/grpctunnel/blob/master/tunnel/tunnel.go#L365)

```text
==================
WARNING: DATA RACE
Read at 0x00c0006fe030 by goroutine 109:
  github.com/openconfig/grpctunnel/tunnel.(*Server).NewSession()
      /home/karim/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20220222153957-e35baf49072c/tunnel/tunnel.go:1001 +0x125
  github.com/openconfig/grpctunnel/tunnel.ServerConn()
      /home/karim/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20220222153957-e35baf49072c/tunnel/conn.go:51 +0x132
//
// redacted
// 

Previous write at 0x00c0006fe030 by goroutine 108:
  runtime.mapassign()
      /home/karim/sdk/go1.17.8/src/runtime/map.go:571 +0x0
  github.com/openconfig/grpctunnel/tunnel.(*Server).addClient()
      /home/karim/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20220222153957-e35baf49072c/tunnel/tunnel.go:365 +0x192
  github.com/openconfig/grpctunnel/tunnel.(*Server).Register()
      /home/karim/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20220222153957-e35baf49072c/tunnel/tunnel.go:772 +0x1b2
  github.com/openconfig/grpctunnel/proto/tunnel._Tunnel_Register_Handler()
      /home/karim/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20220222153957-e35baf49072c/proto/tunnel/tunnel_grpc.pb.go:136 +0xbe
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/karim/go/pkg/mod/google.golang.org/grpc@v1.44.0/server.go:1540 +0x1ab7
```
This case happens when a tunnel server receives a `Register` RPC at the same time a new session is being created.
The trace above show the case of a client addition, but the same could happen when a client is deleted [here](https://github.com/openconfig/grpctunnel/blob/master/tunnel/tunnel.go#L384)

I believe a simple fix is wrapping the `len(s.clients)` call in `s.cmu.Rlock` and `s.cmu.RUnlock()` calls. Or wrapping the whole `NewSession` call in a reader lock.

If you are ok with the issue and the fix, I will submit a PR.

**Comment by hellt** [comment]
Hi @gcsl @gwizdms 
Can you please have a look at this?

**Comment by gcsl** [comment]
Yes, there are several unprotected accesses to s.clients in that function that need to be protected.  The entirety of the accesses should be under the same read lock as they are used to size structures accessed within the loop that could be incorrect if a lock is released in between and lead to deadlock (line 1033).  This will require a bit of refactoring because the lock needs to be released before the wg.Wait on line 1042. Looking at a proper fix....

**Comment by gcsl** [comment]
Fix is pushed.

**Comment by hellt** [comment]
thanks Karim for bringing this up!
