### ISSUE TITLE
How to avoid `target registration (<target.ID>, <target.Type>) not accepted by server`

### ISSUE THREAD

**Issue by yhzs8** [openconfig/grpctunnel#67]
Version: `v0.0.0-20220524190229-125331eabdde`

I got this from time to time during the scenario:

* Targets are registered properly.
* The gRPC connection is broken
* The gRPC connection is restored
* Try to do `tunnel.NewClient()`, `client.Register()` and `client.Start()` immediately. (during `tunnel.NewClient()` I am sending in targets in `ts map[Target]struct{}` so they would be added to the server during `client.Register()`)

Anything I can try to do before `client.Register()` and `client.Start()` to get rid of this error?

**Comment by seanmadell** [comment]
Update: I printed out the `target.Error` when the issue happens [on this line](https://github.com/openconfig/grpctunnel/blob/6f5422b8ca70fad4504571ebc5ce98b74055abef/tunnel/tunnel.go#L1310)
and it seems the error is originated [here](https://github.com/openconfig/grpctunnel/blob/6f5422b8ca70fad4504571ebc5ce98b74055abef/tunnel/tunnel.go#L398)

So I will try to remove the targets before adding them back again when the gRPC connection is restored.

**Comment by yhzs8** [comment]
Update: I printed out the target.Error when the issue happens [on this line](https://github.com/openconfig/grpctunnel/blob/6f5422b8ca70fad4504571ebc5ce98b74055abef/tunnel/tunnel.go#L1310)
and it seems the error is originated [here](https://github.com/openconfig/grpctunnel/blob/6f5422b8ca70fad4504571ebc5ce98b74055abef/tunnel/tunnel.go#L398)

So I will try to remove the targets before adding them back again when the gRPC connection is restored.
